language: python
python:
  - "2.7"
install:
  - pip install 'fabric<2.0'
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
  - xvfb-run fab test