language: python
python:
  - "2.7"
install:
  - pip install 'fabric<2.0'
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - fab test